# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 434)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GENERATOR = QtWidgets.QTabWidget(self.centralwidget)
        self.GENERATOR.setGeometry(QtCore.QRect(10, 0, 551, 391))
        self.GENERATOR.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.GENERATOR.setUsesScrollButtons(False)
        self.GENERATOR.setDocumentMode(False)
        self.GENERATOR.setTabsClosable(False)
        self.GENERATOR.setMovable(True)
        self.GENERATOR.setTabBarAutoHide(False)
        self.GENERATOR.setObjectName("GENERATOR")
        self.PDS = QtWidgets.QWidget()
        self.PDS.setObjectName("PDS")
        self.label = QtWidgets.QLabel(self.PDS)
        self.label.setGeometry(QtCore.QRect(36, 50, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.PDS)
        self.label_2.setGeometry(QtCore.QRect(36, 80, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.PDS)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 61, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.PDS)
        self.pushButton.setGeometry(QtCore.QRect(450, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.PDS)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 80, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.PDS)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 110, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.PDS)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 140, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.PDS)
        self.label_4.setGeometry(QtCore.QRect(36, 140, 61, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.PDS)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 240, 71, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.progressBar = QtWidgets.QProgressBar(self.PDS)
        self.progressBar.setGeometry(QtCore.QRect(110, 240, 411, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.PDS)
        self.label_5.setGeometry(QtCore.QRect(26, 290, 51, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.PDS)
        self.label_6.setGeometry(QtCore.QRect(200, 20, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.PDS)
        self.label_7.setGeometry(QtCore.QRect(86, 190, 101, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.PDS)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 190, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.PDS)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 320, 71, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.PDS)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 50, 331, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.PDS)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 80, 331, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.PDS)
        self.lineEdit_13.setGeometry(QtCore.QRect(110, 110, 331, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.PDS)
        self.lineEdit_14.setGeometry(QtCore.QRect(110, 140, 331, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.PDS)
        self.lineEdit_15.setGeometry(QtCore.QRect(200, 190, 241, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.PDS)
        self.lineEdit_16.setGeometry(QtCore.QRect(80, 290, 331, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.GENERATOR.addTab(self.PDS, "")
        self.EPESSURAGE = QtWidgets.QWidget()
        self.EPESSURAGE.setObjectName("EPESSURAGE")
        self.label_16 = QtWidgets.QLabel(self.EPESSURAGE)
        self.label_16.setGeometry(QtCore.QRect(16, 290, 51, 20))
        self.label_16.setObjectName("label_16")
        self.pushButton_16 = QtWidgets.QPushButton(self.EPESSURAGE)
        self.pushButton_16.setGeometry(QtCore.QRect(430, 70, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.progressBar_3 = QtWidgets.QProgressBar(self.EPESSURAGE)
        self.progressBar_3.setGeometry(QtCore.QRect(100, 240, 411, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_17 = QtWidgets.QPushButton(self.EPESSURAGE)
        self.pushButton_17.setGeometry(QtCore.QRect(430, 110, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_19 = QtWidgets.QPushButton(self.EPESSURAGE)
        self.pushButton_19.setGeometry(QtCore.QRect(430, 170, 75, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_17 = QtWidgets.QLabel(self.EPESSURAGE)
        self.label_17.setGeometry(QtCore.QRect(66, 170, 101, 20))
        self.label_17.setObjectName("label_17")
        self.pushButton_20 = QtWidgets.QPushButton(self.EPESSURAGE)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 240, 71, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.EPESSURAGE)
        self.pushButton_21.setGeometry(QtCore.QRect(430, 320, 71, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_18 = QtWidgets.QLabel(self.EPESSURAGE)
        self.label_18.setGeometry(QtCore.QRect(16, 70, 61, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.EPESSURAGE)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 61, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.EPESSURAGE)
        self.label_20.setGeometry(QtCore.QRect(170, 30, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.EPESSURAGE)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 70, 331, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.EPESSURAGE)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 110, 331, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.EPESSURAGE)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 170, 241, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.EPESSURAGE)
        self.lineEdit_10.setGeometry(QtCore.QRect(80, 290, 331, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.GENERATOR.addTab(self.EPESSURAGE, "")
        self.ROOTAGE = QtWidgets.QWidget()
        self.ROOTAGE.setObjectName("ROOTAGE")
        self.label_9 = QtWidgets.QLabel(self.ROOTAGE)
        self.label_9.setGeometry(QtCore.QRect(26, 280, 51, 20))
        self.label_9.setObjectName("label_9")
        self.progressBar_2 = QtWidgets.QProgressBar(self.ROOTAGE)
        self.progressBar_2.setGeometry(QtCore.QRect(110, 230, 411, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.ROOTAGE)
        self.pushButton_10.setGeometry(QtCore.QRect(460, 90, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.ROOTAGE)
        self.pushButton_12.setGeometry(QtCore.QRect(430, 150, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_10 = QtWidgets.QLabel(self.ROOTAGE)
        self.label_10.setGeometry(QtCore.QRect(66, 150, 101, 20))
        self.label_10.setObjectName("label_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.ROOTAGE)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 230, 71, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.ROOTAGE)
        self.pushButton_14.setGeometry(QtCore.QRect(440, 310, 71, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_12 = QtWidgets.QLabel(self.ROOTAGE)
        self.label_12.setGeometry(QtCore.QRect(16, 90, 91, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.ROOTAGE)
        self.label_13.setGeometry(QtCore.QRect(150, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.ROOTAGE)
        self.lineEdit_17.setGeometry(QtCore.QRect(120, 90, 331, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.ROOTAGE)
        self.lineEdit_18.setGeometry(QtCore.QRect(200, 150, 211, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.ROOTAGE)
        self.lineEdit_19.setGeometry(QtCore.QRect(80, 280, 331, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.GENERATOR.addTab(self.ROOTAGE, "")
        self.ETIQUITE = QtWidgets.QWidget()
        self.ETIQUITE.setObjectName("ETIQUITE")
        self.label_22 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_22.setGeometry(QtCore.QRect(36, 140, 61, 20))
        self.label_22.setObjectName("label_22")
        self.pushButton_22 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_22.setGeometry(QtCore.QRect(450, 110, 75, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_23 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_23.setGeometry(QtCore.QRect(26, 290, 51, 20))
        self.label_23.setObjectName("label_23")
        self.pushButton_23 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_23.setGeometry(QtCore.QRect(450, 50, 75, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.progressBar_4 = QtWidgets.QProgressBar(self.ETIQUITE)
        self.progressBar_4.setGeometry(QtCore.QRect(110, 240, 411, 23))
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName("progressBar_4")
        self.pushButton_24 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_24.setGeometry(QtCore.QRect(450, 80, 75, 23))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_25.setGeometry(QtCore.QRect(450, 140, 75, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_26.setGeometry(QtCore.QRect(450, 190, 75, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_24 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_24.setGeometry(QtCore.QRect(86, 190, 101, 20))
        self.label_24.setObjectName("label_24")
        self.pushButton_27 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_27.setGeometry(QtCore.QRect(20, 240, 71, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.ETIQUITE)
        self.pushButton_28.setGeometry(QtCore.QRect(440, 320, 71, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.label_25 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_25.setGeometry(QtCore.QRect(36, 50, 61, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_26.setGeometry(QtCore.QRect(36, 80, 61, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_27.setGeometry(QtCore.QRect(220, 20, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.ETIQUITE)
        self.label_28.setGeometry(QtCore.QRect(40, 110, 61, 20))
        self.label_28.setObjectName("label_28")
        self.lineEdit = QtWidgets.QLineEdit(self.ETIQUITE)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 331, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.ETIQUITE)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 80, 331, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.ETIQUITE)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 110, 331, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.ETIQUITE)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 140, 331, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.ETIQUITE)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 190, 251, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.ETIQUITE)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 290, 331, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.GENERATOR.addTab(self.ETIQUITE, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.GENERATOR.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GENERATOR.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "BOITE File "))
        self.label_2.setText(_translate("MainWindow", "cable File"))
        self.label_3.setText(_translate("MainWindow", "zapPbo File"))
        self.pushButton.setText(_translate("MainWindow", "Browser"))
        self.pushButton_2.setText(_translate("MainWindow", "Browser"))
        self.pushButton_3.setText(_translate("MainWindow", "Browser"))
        self.pushButton_4.setText(_translate("MainWindow", "Browser"))
        self.label_4.setText(_translate("MainWindow", "casseteFile"))
        self.pushButton_5.setText(_translate("MainWindow", "Start"))
        self.label_5.setText(_translate("MainWindow", "OUTPUT"))
        self.label_6.setText(_translate("MainWindow", "PDS GENERATOR"))
        self.label_7.setText(_translate("MainWindow", "Chose Output Folder"))
        self.pushButton_6.setText(_translate("MainWindow", "Browser"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.GENERATOR.setTabText(self.GENERATOR.indexOf(self.PDS), _translate("MainWindow", "PDS"))
        self.label_16.setText(_translate("MainWindow", "OUTPUT"))
        self.pushButton_16.setText(_translate("MainWindow", "Browser"))
        self.pushButton_17.setText(_translate("MainWindow", "Browser"))
        self.pushButton_19.setText(_translate("MainWindow", "Browser"))
        self.label_17.setText(_translate("MainWindow", "Chose Output Folder"))
        self.pushButton_20.setText(_translate("MainWindow", "Start"))
        self.pushButton_21.setText(_translate("MainWindow", "Close"))
        self.label_18.setText(_translate("MainWindow", "BOITE File "))
        self.label_19.setText(_translate("MainWindow", "PDS File"))
        self.label_20.setText(_translate("MainWindow", "EPESSURAGE"))
        self.GENERATOR.setTabText(self.GENERATOR.indexOf(self.EPESSURAGE), _translate("MainWindow", "EPESSURAGE"))
        self.label_9.setText(_translate("MainWindow", "OUTPUT"))
        self.pushButton_10.setText(_translate("MainWindow", "Browser"))
        self.pushButton_12.setText(_translate("MainWindow", "Browser"))
        self.label_10.setText(_translate("MainWindow", "Chose Output Folder"))
        self.pushButton_13.setText(_translate("MainWindow", "Start"))
        self.pushButton_14.setText(_translate("MainWindow", "Close"))
        self.label_12.setText(_translate("MainWindow", "EPESSURAGE File"))
        self.label_13.setText(_translate("MainWindow", "                       ROUTAGE"))
        self.GENERATOR.setTabText(self.GENERATOR.indexOf(self.ROOTAGE), _translate("MainWindow", "ROUTAGE"))
        self.label_22.setText(_translate("MainWindow", "casseteFile"))
        self.pushButton_22.setText(_translate("MainWindow", "Browser"))
        self.label_23.setText(_translate("MainWindow", "OUTPUT"))
        self.pushButton_23.setText(_translate("MainWindow", "Browser"))
        self.pushButton_24.setText(_translate("MainWindow", "Browser"))
        self.pushButton_25.setText(_translate("MainWindow", "Browser"))
        self.pushButton_26.setText(_translate("MainWindow", "Browser"))
        self.label_24.setText(_translate("MainWindow", "Chose Output Folder"))
        self.pushButton_27.setText(_translate("MainWindow", "Start"))
        self.pushButton_28.setText(_translate("MainWindow", "Close"))
        self.label_25.setText(_translate("MainWindow", "BOITE File "))
        self.label_26.setText(_translate("MainWindow", "cable File"))
        self.label_27.setText(_translate("MainWindow", "ETIQUETTE"))
        self.label_28.setText(_translate("MainWindow", "zapPbo File"))
        self.GENERATOR.setTabText(self.GENERATOR.indexOf(self.ETIQUITE), _translate("MainWindow", "ETIQUETE"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
